import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import config.ApplicationConfig2;
import config.user.service.impl.UserService;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    
    public static void main(String[] args) {
//    	AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext("config..*");
    	AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext(ApplicationConfig2.class);
//    	ISomethingService s = (ISomethingService) ctx.getBean("somethingService");
//    	s.doesTest();
//    	s.hello();
//    	ctx.refresh();
//    	System.out.println(ApplicationConfig.AOP_POINTCUT_EXPRESSION);
    	
    	UserService service = (UserService) ctx.getBean("userService");
    	service.getAndPrint(1);
    	service.getAndPrint(1);
//    	service.doTake();
//    	service.doUpdateUserName(1);
	}
}
